
- path: 
    - /news/twitter
  controller: Controllers\TwitterController::getTweets

- path: 
    - /map
  controller: Controllers\MapController::index

- path:
    - 
  controller: Controllers\TodoController::index

