
- path:
  -
  controller: Controllers\HomeController::render

- path:
  - /buy
  controller: Controllers\LocalbitcoinsController::render

- path:
  - /news/twitter
  controller: Controllers\TwitterController::getTweets

- path:
  - /news/youtube
  controller: Controllers\YoutubeController::render

- path:
  - /faq
  controller: Controllers\FaqController::render
